import { useMemo, useState } from "react";
import type { ConnectorMemorySource } from "../api/types";
import { useActions, useConversation, useDispatch, useResults, useUi } from "../hooks";
import { useChatLens } from "../hooks/useChatLens";
import { SearchHero } from "../features/results/SearchHero";
import { ResultsHeader } from "../features/results/ResultsHeader";
import { MemoryGrid } from "../features/results/MemoryGrid";
import { SourceFilter, type SourceFilterValue } from "../features/results/SourceFilter";
import { ImageDetailDrawer } from "../features/results/ImageDetailDrawer";
import { ConversationPanel } from "../features/conversation/ConversationPanel";
import { ActionPanel } from "../features/actions/ActionPanel";
import { SummaryPanel } from "../features/actions/SummaryPanel";
import { RoadmapPanel } from "../features/actions/RoadmapPanel";
import { ConfirmDialog } from "../features/actions/ConfirmDialog";
import { SkeletonGrid } from "../components/SkeletonGrid";
import { EmptyState, ErrorState, NotConnectedState } from "../components/States";
import { Icon } from "../components/Icon";

export function SearchWorkspace() {
  const results = useResults();
  const conversation = useConversation();
  const actions = useActions();
  const ui = useUi();
  const dispatch = useDispatch();
  const c = useChatLens();
  const [view, setView] = useState<"grid" | "list">("grid");
  const [source, setSource] = useState<SourceFilterValue>("all");

  // Sources actually present in the current results (no invented options).
  const availableSources = useMemo(() => {
    const set = new Set<ConnectorMemorySource>();
    results.items.forEach((r) => { if (r.memorySource) set.add(r.memorySource); });
    return [...set];
  }, [results.items]);

  const visibleItems = useMemo(
    () => (source === "all" ? results.items : results.items.filter((r) => r.memorySource === source)),
    [results.items, source]
  );

  // Drawer only opens for a real, currently-loaded result (no demo lookup).
  const openResult = results.items.find((r) => r.id === ui.drawerOpenForId);

  return (
    <div>
      {!results.hasSearched ? (
        <SearchHero onSearch={c.runSearch} onUpload={() => dispatch({ type: "VIEW_CHANGED", view: "upload" })} />
      ) : (
        <div className="workspace">
          <div className="results-col">
            <ResultsHeader
              query={results.echoedQuery}
              count={visibleItems.length}
              clues={conversation.activeClues}
              view={view}
              refining={results.refining}
              onRemoveClue={c.removeClue}
              onToggleView={setView}
            />

            {availableSources.length > 0 && (
              <SourceFilter available={availableSources} value={source} onChange={setSource} />
            )}

            {results.loading ? (
              <SkeletonGrid count={6} />
            ) : results.notConnected ? (
              <NotConnectedState />
            ) : results.error ? (
              <ErrorState title="Search failed" message={results.error} onRetry={() => c.runSearch(results.echoedQuery)} />
            ) : visibleItems.length === 0 ? (
              <EmptyState
                icon="search"
                title="No memories matched"
                message="Try adding a memory clue - for example the type of image, a topic, or something you remember seeing."
              />
            ) : (
              <MemoryGrid
                results={visibleItems}
                selectedIds={results.selectedIds}
                view={view}
                onToggleSelect={c.toggleSelect}
                onOpen={c.openDrawer}
                onWhy={c.openDrawer}
              />
            )}
          </div>

          <div className="side-col">
            <ConversationPanel onSend={c.runRefine} />
            <ActionPanel
              selectedCount={results.selectedIds.length}
              loading={actions.loading}
              onSummarize={c.summarize}
              onRoadmap={c.makeRoadmap}
            />
            {actions.notConnected && (
              <div className="panel"><div className="panel-body">
                <NotConnectedState
                  title="Actions need the backend"
                  message="Summaries and roadmaps are generated by the ChatLens agent. Connect the backend to use them."
                />
              </div></div>
            )}
            {actions.summary && <SummaryPanel summary={actions.summary} resultItems={results.items} onRoadmap={c.makeRoadmap} />}
            {actions.roadmap && (
              <RoadmapPanel roadmap={actions.roadmap} onSchedule={() => c.proposeSchedule(actions.roadmap!.steps)} />
            )}
            <button className="btn btn-ghost" style={{ width: "100%" }} onClick={() => c.runSearch(results.echoedQuery)}>
              <Icon name="search" size={16} /> New search
            </button>
          </div>
        </div>
      )}

      {openResult && (
        <ImageDetailDrawer
          result={openResult}
          selected={results.selectedIds.includes(openResult.id)}
          onClose={c.closeDrawer}
          onToggleSelect={c.toggleSelect}
          onSummarize={c.summarizeImage}
          onRoadmap={c.roadmapImage}
        />
      )}
      {ui.confirmDialogOpen && actions.proposal && (
        <ConfirmDialog
          proposal={actions.proposal}
          onConfirm={() => c.confirmSchedule(actions.proposal!.events)}
          onCancel={c.cancelSchedule}
        />
      )}
    </div>
  );
}